import type { Metadata } from "next";
import "./globals.css";

import { yekan } from "@/utils/fonts";
import { ClientProdiver, NextAuthProvider } from "../providers";
import { Layout } from "src/components";
import { Toaster } from "react-hot-toast";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="fa" dir="rtl">
      <body className={yekan.className}>
        <NextAuthProvider>
          <ClientProdiver>
            <Layout>{children}</Layout>
          </ClientProdiver>
        </NextAuthProvider>
        <Toaster />
      </body>
    </html>
  );
}
